### ISSUE TITLE
Bug with GHOST

### ISSUE THREAD

**Issue by thely** [pippinbarr/chesses3#1]
A fun bug: if you start Ghost, and then return to the menu, the Ghost music is still playing. If you choose to then start Ghost again, the original audio node is still playing, but a new one starts on top of it. I was able to get this up to five recognizably separate-but-simultaneous audio nodes before I couldn't pick out the new ones anymore. It was messy, but sonically very interesting!

**Comment by pippinbarr** [comment]
Fun indeed! I know the kind of thing this is and will fix it, but totally agree it can also sound interesting :)
